//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebook_Store.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBook
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Author { get; set; }
        public string Category { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Status { get; set; }
        public string Process { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Image { get; set; }
        public Nullable<int> Admin_Id { get; set; }
        public Nullable<int> Seller_Id { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
